Add missing changelog for 1.0.0
not-an-aardvark/pk6parse pull request #24
Opened 2017-02-16 15:04 UTC by YaManicKill

2017-02-16 16:14 UTC, not-an-aardvark requested changes

2017-02-16 16:14 UTC, not-an-aardvark commented on CHANGELOG.md
> +* idNo is now either a 5 digit tid for gen 6, or 6 digit tid for gen 7
We should also probably mention `fullTid` somewhere, and the fact that `tid` and `sid` are now deprecated.

2017-02-16 16:14 UTC, not-an-aardvark commented on CHANGELOG.md
> +* Added support for pk7s (need to pass gen=7 option to parser)
Can you also update the documentation for this function in the readme?

2017-02-16 16:14 UTC, not-an-aardvark commented on CHANGELOG.md
> +
If I recall correctly, there were some other breaking changes too (e.g. relating to how ribbon data is stored). We should document all the breaking changes.

2017-02-16 16:31 UTC, YaManicKill commented on CHANGELOG.md
> +
The ribbon changes were reverted. I can't think of any breaking changes, but I'll see if @SnowPhoenix can think of any.

2017-02-16 16:31 UTC, YaManicKill commented on CHANGELOG.md
> +* idNo is now either a 5 digit tid for gen 6, or 6 digit tid for gen 7
Yeah, good plan.

2017-02-16 16:32 UTC, YaManicKill commented on CHANGELOG.md
> +* Added support for pk7s (need to pass gen=7 option to parser)
I already did that. Unless there's something specific you think I've missed.

2017-02-16 17:11 UTC, not-an-aardvark commented on CHANGELOG.md
> +* Added support for pk7s (need to pass gen=7 option to parser)
You're right, never mind. (Now that I think about it we might also want to document `pkparse.SUPPORTED_GENS`, but that's probably less important.)

2017-02-17 07:38 UTC, YaManicKill commented on CHANGELOG.md
> +* Added support for pk7s (need to pass gen=7 option to parser)
Done :-)

2017-02-17 07:40 UTC, not-an-aardvark approved these changes

2017-02-17 07:51 UTC, merged